### ISSUE TITLE
Whats is the HFT-Orderbook's main use ?

### ISSUE THREAD

**Issue by samholt** [nlsdfnbch/HFT-Orderbook#10]
Love this implementation;

Wondering what you find the main use of it is ?

Noticed your implementation of Websocket API's for other cryptocurrency exchanges, 
Would you be interested in collaborating on a joint websocket api project ?

Best,
Sam

**Comment by nlsdfnbch** [comment]
Hey @samholt ,

glad to hear you like it! 
Regarding its use, it was actually just a C excercise. Using it to compile a cross-exchange book would be a use case for it indeed. Coming from crypto, the difficulty with that is though, that it requires an order ID for every order. 
While some exchanges provide that, many of them do not (some do not even provide level3 book data) - which makes order tracking difficult this way.  Which is why my systems usually only track level 2 books and disregard granular order specifics. 

That's an entirely different scenario, of course, for "proper" financial instruments. Being what it is, crypto is still very much in its baby shoes.

What type of collaboration did you have in mind?

Cheers,

Nils

btw: Pardon that I didn't mail you instead of replying here - I'm currently abroad and it appears my mail service is being blocked.

**Comment by samholt** [comment]
Excellent,

Currently extending https://github.com/ccxt/ccxt, to implement Websocket's for all the exchanges that support it. Love your previous work on your Websocket's for: https://github.com/nlsdfnbch/bitex. Would you be interested in helping us port it over to ccxt, and begin to integrate all the api functionality alongside the other 90 exchanges, with our active dev team.

Eventually would like to add certain features, such as creating an synthetic order book using most of what you have here with the HFT-Orderbook's, its very well designed and documented.

**Comment by nlsdfnbch** [comment]
Absolutely! Although I would like to point out that the websocket were a beta, which since then hasn't been improved. Especially the bitfinex one should perhaps be replaced, depending on what you need. 
I have had a look at ccxt  in the past and was quite impressed.

**Comment by nlsdfnbch** [comment]
Do you have a slack or gitter channel on which we could discuss the implementation?

**Comment by nlsdfnbch** [comment]
Closing this, moved to gitter :)
